/**
 * UI5 Linter Configuration (CommonJS)
 *
 * Use this configuration file for traditional Node.js projects.
 * Place this file in your project root (same directory as ui5.yaml and package.json).
 *
 * Documentation: https://github.com/UI5/linter/blob/main/README.md
 */

module.exports = {
  /**
   * Ignore Patterns
   *
   * Array of glob patterns to exclude files from linting.
   * Patterns are relative to project root.
   * Use '!' prefix for negation (include files despite earlier ignore).
   * Pattern order matters - later patterns override earlier ones.
   */
  ignores: [
    // Third-party libraries (no control over code quality)
    "webapp/thirdparty/**",
    "webapp/vendor/**",

    // Mock data and local services (often auto-generated)
    "webapp/localService/**",

    // Test files (optional - remove if you want to lint tests)
    "webapp/test/**",

    // Include integration tests (negation example)
    "!webapp/test/integration/**",

    // Build output directories
    "dist/**",
    "build/**",

    // Minified files (already optimized, no need to lint)
    "**/*.min.js",
    "**/*.bundle.js",

    // UI Adaptation changes (generated by Fiori)
    "webapp/changes/**",
  ],

  /**
   * File Patterns (Optional)
   *
   * Array of glob patterns specifying which files to lint.
   * If omitted, all files in the project are linted (except ignores).
   *
   * Uncomment and customize if you want to lint specific files only:
   */
  // files: [
  //   "webapp/**/*.js",
  //   "webapp/**/*.xml",
  //   "webapp/manifest.json",
  // ],
};
